# Site settings
title: Results
email: jonahphilion@college.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  jonahphilion@college.harvard.edu
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  jonahthelion

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  physics:
    output: true
    permalink: /physics/:path/
  music:
    output: true
    permalink: /music/:path/


